~GATE
/frs"BAD_CALL"hdfrs"GATE"hgeprs"BAD_CALL"hc.fri-5hnep.fri3hnep.ri-1ri0hnep.frs"cats"hgep.frs"H1"hgep.rs"f2"rs"H2"hgepV
/V...................................................................................................................<
/>rs"hot"fri-4hs.rs"hot"hc.rs"f2"ri0hl.rs"f2"ri0hd.rs"f2"ri0hl.rnfri-5hs.fri-5hnep.ri-5hc.e~ha
~BAD_CALL
/>{
/>rs"hello"ephr
~H1
/>rs"h1"ephr
+f2
~H2
/rs"h2"ephr
